stages:
  - build
variables:
  GIT_SUBMODULE_STRATEGY: recursive

build_images:
  stage: build
  image: registry.gloria-jeans.ru/gitlab/netcore:28.0.3.v1
  tags:
    - dind
    - docker

  script:
    - VERSION=$(git rev-list --all --count)
    - sed -i -r 's/<Version>([0-9]*)\.([0-9])*\.[0-9]*/<Version>\1.\2.'"$VERSION"'/' CoreNetCore/CoreNetCore.csproj
    - echo $VERSION
    - dotnet build -c release CoreNetCore
    - dotnet nuget push -s http://haproxy.lb.dbs.grp.gloria-jeans.ru:1080/v3/index.json CoreNetCore/bin/release/CoreNetCore*.nupkg

  only:
    - master
