stages:
  - build
variables:
  GIT_SUBMODULE_STRATEGY: recursive

build_images:
  stage: build
  image: registry.gloria-jeans.ru/gitlab/netcore:28.0.3.v1
  tags:
    - dind
    - docker

  script:
    - dotnet build -c release CoreNetCore


  only:
    - master
